# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

test-warnings: true
strictness: medium
max-line-length: 140
uses:
  - django
  - celery
requirements:
  - requirements/common.txt
  - requirements/dev.txt
# We run flake8 (pep8 + pyflakes) as part of the Travis run,
# so it's unnecessary to run them again here.
pep8:
  run: false
pyflakes:
  run: false
